version: '3'

services:

  db:
    image: mysql:8.0
    command: mysqld --user=mysql --innodb-use-native-aio=0
    env_file:
      - .env
    volumes:
      - ./db-datadir:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307"
    tty: true

  app:
    build:
      context: ./
    container_name: happy-valentine
    command: sh -c "./wait-for-it.sh db:3306"
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
